version: '3.4'

services:
  webapi:
    restart: unless-stopped
    env_file: .env
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_HTTP_PORTS=8080
      - ConnectionStrings__Default=${CONNECTIONSTRINGS_DEFAULT}
      - TZ=${TZ}
    ports:
      - "${WEBAPI_PORT}:8080"