version: "3.4"

services:
  webapi:
    build:
      context: .
      dockerfile: src/Mall.WebApi/Dockerfile
    env_file: .env
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
      - ConnectionStrings__Default=${CONNECTIONSTRINGS_DEFAULT}
      - TZ=${TZ}
    ports:
      - "${WEBAPI_PORT}:8080"
    volumes:
      - ${APPDATA}/ASP.NET/Https:/home/app/.aspnet/https:ro
