name: Release

on:
  push:
    branches: ['release/**']
  release:
    types: [published]

jobs:
  publish:
    runs-on: ubuntu-latest
    env:
      NUGET_API_KEY: ${{secrets.NUGET_API_KEY}}

    steps:
    - uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        global-json-file: ./global.json

    - name: Build and Test
      run: ./build.sh --target=package

    - name: Push Nuget
      run: ./build.sh --target=publishnuget
